version: "2.1"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:9200/_cluster/health"]
      interval: 5s
      timeout: 5s
      retries: 15
    logging:
      driver: none
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
